### ISSUE TITLE
State ?

### ISSUE THREAD

**Issue by melMass** [mottosso/allspark#27]
I Mottosso,
This looks great I just wanted to know the current status of the project? 
From the issues, it seems there are only cosmetic issues left? 

Thanks for making `bleeding-rez` 🙏

**Comment by mottosso** [comment]
Hi @melMass, thanks for the kind words. It's early still, come back in August. You can follow the progress here: #1 and at https://allspark.sh. I'll update the README of this repo with instructions once it's ready for use.

**Comment by mottosso** [comment]
@melMass it's ready! :D
